### ISSUE TITLE
EYLogger :success and :failure hooks never called

### ISSUE THREAD

**Issue by cgriego** [engineyard/eycap#3]
It's caused by this line:
http://github.com/engineyard/eycap/blob/master/lib/eycap/lib/ey_logger.rb#L66

After that statement runs, hooks evaluates to either [:any, true] or [:any, false] so it's appending the result of successful? rather than the terninary. Some parenthesis to force the operational order will fix the issue. I kept going around in circles trying to figure out what was wrong with either my task or my hook registration code.

**Comment by cgriego** [comment]
I have a fork with this fix. http://github.com/cgriego/eycap/commit/03abb2ca3e7fbc12a451fe02f9393055ed8e1982

**Comment by crigor** [comment]
This is fixed on master. Thanks cgriego!
